#### Render Blueprint specification: https://dashboard.render.com/blueprints ####
## 👇 Preview environments: https://render.com/docs/preview-environments ###
# previewsEnabled: true
## 👇 Automatically nuke the environment after X days of inactivity to reduce billing:
# previewsExpireAfterDays: 2
services:
  - type: web
    name: podkastify-web
    env: node
    plan: free
    ## 👇 Specify the plan for the PR deployment:
    # previewPlan: starter
    ## 👇 Preview Environment Initialization script:
    # initialDeployHook: pnpm db-seed
    buildCommand: pnpm install && pnpm db:migrate && pnpm build
    startCommand: pnpm --filter=web prod
    # healthCheckPath: /api/trpc/healthcheck
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: podkastify-db
          property: connectionString
      - key: PORT
        value: 3000
      - key: NEXT_PUBLIC_TRPC_URL
        sync: false # provide this in the Render dashboard.

  - type: web
    name: podkastify-api
    env: node
    plan: free
    ## 👇 Specify the plan for the PR deployment:
    # previewPlan: starter
    ## 👇 Preview Environment Initialization script:
    # initialDeployHook: pnpm db-seed
    buildCommand: |
      pip install yt-dlp ffmpeg ffprobe &&
      pnpm install &&
      pnpm db:migrate:deploy &&
      pnpm build
    startCommand: pnpm --filter=server prod
    # healthCheckPath: /api/trpc/healthcheck
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: podkastify-db
          property: connectionString
      - key: PORT
        value: 3001
      - key: JWT_SECRET
        sync: false # provide this in the Render dashboard.
      - key: MAGIC_LOGIN_LINK_EXPIRES_IN
        sync: false # provide this in the Render dashboard.
      - key: MAIL_SMTP_HOST
        sync: false # provide this in the Render dashboard.
      - key: MAIL_SMTP_PORT
        sync: false # provide this in the Render dashboard.
      - key: MAIL_SMTP_SECURE
        sync: false # provide this in the Render dashboard.
      - key: MAIL_SMTP_USERNAME
        sync: false # provide this in the Render dashboard.
      - key: MAIL_SMTP_PASSWORD
        sync: false # provide this in the Render dashboard.
      - key: MAIL_DEFAULT_FROM
        sync: false # provide this in the Render dashboard.
      - key: EMAILS_ENABLED
        sync: false # provide this in the Render dashboard.

databases:
  - name: podkastify-db
    plan: free
